Make -j only when CPU cores number is greater than 1. Fix dropbox permission bug

diff --git a/start b/start
--- a/start
+++ b/start
@@ -2,7 +2,7 @@
 
 # Start dropbox if needed
 if [[ -n $(dropbox start | grep 'following') ]]; then
-  exit 1
+  echo "error starting dropbox" && exit 1
 fi
 
 rm -rf results/*
